name: Notify Discord on PR to Main

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_USER: ${{ github.event.pull_request.user.login }}
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"A new PR was opened on main by $PR_USER: [$PR_TITLE]($PR_URL)\"}" \
            $DISCORD_WEBHOOK